# Generated by Django 5.2.3 on 2025-07-11 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Germinacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_ingreso", models.DateField(verbose_name="Fecha de ingreso")),
                (
                    "fecha_polinizacion",
                    models.DateField(verbose_name="Fecha de polinización"),
                ),
                (
                    "dias_polinizacion",
                    models.PositiveIntegerField(verbose_name="Días desde polinización"),
                ),
                (
                    "nombre",
                    models.CharField(max_length=255, verbose_name="Nombre del híbrido"),
                ),
                (
                    "detalles_padres",
                    models.TextField(verbose_name="Detalles de padres del híbrido"),
                ),
                (
                    "tipo_polinizacion",
                    models.CharField(
                        max_length=100, verbose_name="Tipo de polinización"
                    ),
                ),
                ("finca", models.CharField(max_length=100)),
                (
                    "numero_vivero",
                    models.CharField(max_length=50, verbose_name="Número de vivero"),
                ),
                (
                    "numero_capsulas",
                    models.PositiveIntegerField(verbose_name="Número de cápsulas"),
                ),
                (
                    "estado_capsulas",
                    models.CharField(
                        choices=[
                            ("BUENO", "Bueno"),
                            ("REGULAR", "Regular"),
                            ("MALO", "Malo"),
                        ],
                        max_length=20,
                        verbose_name="Estado de cápsulas",
                    ),
                ),
                (
                    "cantidad_solicitada",
                    models.PositiveIntegerField(verbose_name="Cantidad solicitada"),
                ),
                (
                    "entrega_capsulas",
                    models.CharField(
                        max_length=255, verbose_name="Persona que entrega las cápsulas"
                    ),
                ),
                (
                    "recibe_capsulas",
                    models.CharField(
                        max_length=255, verbose_name="Persona que recibe las cápsulas"
                    ),
                ),
                (
                    "etapa_actual",
                    models.CharField(
                        choices=[
                            ("SIEMBRA", "Siembra"),
                            ("GERMINACION", "Germinación"),
                            ("CRECIMIENTO", "Crecimiento"),
                            ("TRASPLANTE", "Trasplante"),
                        ],
                        default="SIEMBRA",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Especie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "genero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="especies",
                        to="laboratorio.genero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Capsula",
            fields=[
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "germinacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capsulas",
                        to="laboratorio.germinacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "germinacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="laboratorio.germinacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("direccion", models.CharField(max_length=255)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Polinizacion",
            fields=[
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_pol", models.DateField(verbose_name="Fecha de polinización")),
                (
                    "fecha_mad",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de maduración"
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("disponible", models.BooleanField(default=True)),
                ("archivo_origen", models.CharField(blank=True, max_length=255)),
                (
                    "fecha_siembra",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de siembra"
                    ),
                ),
                (
                    "fecha_replante",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de replante"
                    ),
                ),
                ("clima", models.CharField(blank=True, max_length=100)),
                ("cantidad_solicitada", models.PositiveIntegerField(default=0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EN_PROCESO", "En proceso"),
                            ("COMPLETADA", "Completada"),
                            ("FALLIDA", "Fallida"),
                        ],
                        default="EN_PROCESO",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="polinizaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ubicacion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="polinizaciones",
                        to="laboratorio.ubicacion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="germinacion",
            name="polinizacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="germinaciones",
                to="laboratorio.polinizacion",
            ),
        ),
        migrations.CreateModel(
            name="SeguimientoGerminacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("cantidad_germinada", models.PositiveIntegerField(default=0)),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("SIEMBRA", "Siembra"),
                            ("GERMINACION", "Germinación"),
                            ("CRECIMIENTO", "Crecimiento"),
                            ("TRASPLANTE", "Trasplante"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "germinacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="laboratorio.germinacion",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seguimientos_germinacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento de germinación",
                "verbose_name_plural": "Seguimientos de germinación",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Siembra",
            fields=[
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "germinacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="siembras",
                        to="laboratorio.germinacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "temporada_inicio",
                    models.CharField(
                        choices=[
                            ("PRIMAVERA", "Primavera"),
                            ("VERANO", "Verano"),
                            ("OTONO", "Otoño"),
                            ("INVIERNO", "Invierno"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "temporada_polinizacion",
                    models.CharField(
                        choices=[
                            ("PRIMAVERA", "Primavera"),
                            ("VERANO", "Verano"),
                            ("OTONO", "Otoño"),
                            ("INVIERNO", "Invierno"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dias_germinacion_min",
                    models.PositiveIntegerField(
                        verbose_name="Días mínimos de germinación"
                    ),
                ),
                (
                    "dias_germinacion_max",
                    models.PositiveIntegerField(
                        verbose_name="Días máximos de germinación"
                    ),
                ),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variedades",
                        to="laboratorio.especie",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="variedad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polinizaciones",
                to="laboratorio.variedad",
            ),
        ),
    ]
