# Generated by Django 5.2.3 on 2025-07-12 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="polinizacion",
            name="especie",
            field=models.CharField(blank=True, max_length=100, verbose_name="Especie"),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="genero",
            field=models.CharField(blank=True, max_length=100, verbose_name="Género"),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="variedad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polinizaciones",
                to="laboratorio.variedad",
            ),
        ),
    ]
