# Generated by Django 5.2.3 on 2025-07-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0002_polinizacion_especie_polinizacion_genero_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="polinizacion",
            old_name="fecha_mad",
            new_name="fechamad",
        ),
        migrations.RenameField(
            model_name="polinizacion",
            old_name="fecha_pol",
            new_name="fechapol",
        ),
        migrations.RemoveField(
            model_name="polinizacion",
            name="cantidad_solicitada",
        ),
        migrations.RemoveField(
            model_name="polinizacion",
            name="clima",
        ),
        migrations.RemoveField(
            model_name="polinizacion",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="polinizacion",
            name="fecha_actualizacion",
        ),
        migrations.RemoveField(
            model_name="polinizacion",
            name="fecha_creacion",
        ),
        migrations.RemoveField(
            model_name="polinizacion",
            name="fecha_replante",
        ),
        migrations.RemoveField(
            model_name="polinizacion",
            name="fecha_siembra",
        ),
        migrations.RemoveField(
            model_name="polinizacion",
            name="observaciones",
        ),
        migrations.RemoveField(
            model_name="polinizacion",
            name="variedad",
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="especie",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="genero",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="responsable",
            field=models.CharField(
                blank=True, default="Sin responsable", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="ubicacion",
            field=models.CharField(blank=True, default="Sin ubicacion", max_length=100),
            preserve_default=False,
        ),
    ]
