# Generated by Django 5.2.4 on 2025-07-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0003_rename_fecha_mad_polinizacion_fechamad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="germinacion",
            name="prediccion",
            field=models.FloatField(blank=True, null=True, verbose_name="Predicción"),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="prediccion",
            field=models.FloatField(blank=True, null=True, verbose_name="Predicción"),
        ),
    ]
