# Generated by Django 5.2.3 on 2025-07-13 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0004_germinacion_prediccion_polinizacion_prediccion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="germinacion",
            name="prediccion",
        ),
        migrations.RemoveField(
            model_name="polinizacion",
            name="prediccion",
        ),
    ]
