# Generated by Django 5.2.3 on 2025-07-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_remove_germinacion_prediccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polinizacion',
            name='tipo_polinizacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de polinización'),
        ),
    ]
