# Generated by Django 5.2.3 on 2025-07-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_polinizacion_tipo_polinizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germinacion',
            name='dias_polinizacion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Días desde polinización'),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='estado_capsulas',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], default='BUENO', max_length=20, verbose_name='Estado de cápsulas'),
        ),
    ]
