# Generated by Django 5.2.3 on 2025-07-31 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_alter_germinacion_dias_polinizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='germinacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='germinaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
