# Generated by Django 5.2.3 on 2025-07-31 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0008_germinacion_creado_por'),
    ]

    operations = [
    ]
