# Generated by Django 5.2.3 on 2025-08-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0010_polinizacion_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='germinacion',
            name='clima',
            field=models.CharField(blank=True, default='templado', max_length=50, null=True, verbose_name='Clima'),
        ),
        migrations.AddField(
            model_name='germinacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='germinacion',
            name='disponibles',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Disponibles'),
        ),
        migrations.AddField(
            model_name='germinacion',
            name='especie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especie'),
        ),
        migrations.AddField(
            model_name='germinacion',
            name='fecha_germinacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de germinación'),
        ),
        migrations.AddField(
            model_name='germinacion',
            name='fecha_siembra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de siembra'),
        ),
        migrations.AddField(
            model_name='germinacion',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='germinacion',
            name='semilla_vana',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Semilla vana'),
        ),
        migrations.AddField(
            model_name='germinacion',
            name='semillas_stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Semillas en stock'),
        ),
        migrations.AddField(
            model_name='germinacion',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='cantidad_solicitada',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cantidad solicitada'),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='detalles_padres',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles de padres del híbrido'),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='entrega_capsulas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Persona que entrega las cápsulas'),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='estado_capsulas',
            field=models.CharField(blank=True, choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], default='BUENO', max_length=20, null=True, verbose_name='Estado de cápsulas'),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='etapa_actual',
            field=models.CharField(blank=True, choices=[('SIEMBRA', 'Siembra'), ('GERMINACION', 'Germinación'), ('CRECIMIENTO', 'Crecimiento'), ('TRASPLANTE', 'Trasplante')], default='SIEMBRA', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='fecha_polinizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de polinización'),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='finca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del híbrido'),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='numero_capsulas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de cápsulas'),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='numero_vivero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de vivero'),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='recibe_capsulas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Persona que recibe las cápsulas'),
        ),
        migrations.AlterField(
            model_name='germinacion',
            name='tipo_polinizacion',
            field=models.CharField(blank=True, choices=[('HIBRIDA', 'Híbrida'), ('REPLANTE', 'Replante'), ('SELF', 'Self'), ('SIBLING', 'Sibling')], max_length=20, null=True, verbose_name='Tipo de polinización'),
        ),
    ]
