# Generated by Django 5.2.3 on 2025-08-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0011_germinacion_clima_germinacion_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germinacion',
            name='estado_capsulas',
            field=models.CharField(blank=True, choices=[('ABIERTO', 'Abierto'), ('CERRADA', 'Cerrada'), ('SEMIABIERTA', 'Semiabierta')], default='CERRADA', max_length=20, null=True, verbose_name='Estado de cápsulas'),
        ),
    ]
