# Generated by Django 5.2.3 on 2025-08-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0012_alter_germinacion_estado_capsulas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germinacion',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('vivero', 'Vivero'), ('mesa', 'Mesa'), ('pared', 'Pared')], default='vivero', max_length=20, null=True, verbose_name='Ubicación'),
        ),
    ]
