# Generated by Django 5.2.3 on 2025-08-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0013_alter_germinacion_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germinacion',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('vivero_1', 'Vivero 1'), ('vivero_2', 'Vivero 2'), ('vivero_3', 'Vivero 3'), ('mesa_a', 'Mesa A'), ('mesa_b', 'Mesa B'), ('mesa_c', 'Mesa C'), ('pared_norte', 'Pared Norte'), ('pared_sur', 'Pared Sur'), ('pared_este', 'Pared Este'), ('pared_oeste', 'Pared Oeste')], default='vivero_1', max_length=20, null=True, verbose_name='Ubicación'),
        ),
    ]
