# Generated by Django 5.2.3 on 2025-08-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0014_alter_germinacion_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germinacion',
            name='etapa_actual',
            field=models.CharField(blank=True, choices=[('INGRESADO', 'Ingresado'), ('EN_PROCESO', 'En proceso'), ('LISTA', 'Lista'), ('CANCELADO', 'Cancelado')], default='INGRESADO', max_length=20, null=True),
        ),
    ]
