# Generated by Django 5.2.3 on 2025-08-10 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0016_remove_germinacion_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AddField(
            model_name='notification',
            name='polinizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='laboratorio.polinizacion'),
        ),
        migrations.AddField(
            model_name='polinizacion',
            name='estado',
            field=models.CharField(choices=[('INGRESADO', 'Ingresado'), ('EN_PROCESO', 'En proceso'), ('LISTO', 'Listo')], default='INGRESADO', max_length=20, verbose_name='Estado de la polinización'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='germinacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='laboratorio.germinacion'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('NUEVA_GERMINACION', 'Nueva Germinación'), ('RECORDATORIO_REVISION', 'Recordatorio de Revisión'), ('ESTADO_ACTUALIZADO', 'Estado Actualizado'), ('NUEVA_POLINIZACION', 'Nueva Polinización'), ('ESTADO_POLINIZACION_ACTUALIZADO', 'Estado de Polinización Actualizado')], max_length=35),
        ),
    ]
