# Generated by Django 5.2.3 on 2025-08-29 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "laboratorio",
            "0017_alter_notification_options_notification_polinizacion_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="germinacion",
            name="tipo_polinizacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HIBRIDA", "Híbrida"),
                    ("SELF", "Self"),
                    ("SIBLING", "Sibling"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de polinización",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("INGRESADO", "Ingresado"),
                    ("EN_PROCESO", "En proceso"),
                    ("LISTA", "Lista"),
                ],
                default="INGRESADO",
                max_length=20,
                verbose_name="Estado de la polinización",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("TIPO_1", "Tipo 1 - Acceso Completo Lab"),
                            ("TIPO_2", "Tipo 2 - Especialista Polinización"),
                            ("TIPO_3", "Tipo 3 - Especialista Germinación"),
                            ("TIPO_4", "Tipo 4 - Administrador"),
                        ],
                        default="TIPO_3",
                        max_length=10,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("departamento", models.CharField(blank=True, max_length=100)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
            },
        ),
    ]
