# Generated by Django 5.2.4 on 2025-08-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0019_auto_20250828_2138"),
    ]

    operations = [
        migrations.AddField(
            model_name="polinizacion",
            name="cantidad_capsulas",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Cantidad de cápsulas"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="madre_clima",
            field=models.CharField(
                default="I", max_length=50, verbose_name="Clima planta madre"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="madre_codigo",
            field=models.CharField(
                default="", max_length=50, verbose_name="Código planta madre"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="madre_especie",
            field=models.CharField(
                default="", max_length=100, verbose_name="Especie/Variedad planta madre"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="madre_genero",
            field=models.CharField(
                default="", max_length=100, verbose_name="Género planta madre"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="nueva_clima",
            field=models.CharField(
                default="I", max_length=50, verbose_name="Clima nueva planta"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="nueva_codigo",
            field=models.CharField(
                default="", max_length=50, verbose_name="Código nueva planta"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="nueva_especie",
            field=models.CharField(
                default="", max_length=100, verbose_name="Especie/Variedad nueva planta"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="nueva_genero",
            field=models.CharField(
                default="", max_length=100, verbose_name="Género nueva planta"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="padre_clima",
            field=models.CharField(
                default="I", max_length=50, verbose_name="Clima planta padre"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="padre_codigo",
            field=models.CharField(
                default="", max_length=50, verbose_name="Código planta padre"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="padre_especie",
            field=models.CharField(
                default="", max_length=100, verbose_name="Especie/Variedad planta padre"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="padre_genero",
            field=models.CharField(
                default="", max_length=100, verbose_name="Género planta padre"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="ubicacion_nombre",
            field=models.CharField(
                default="", max_length=100, verbose_name="Nombre de ubicación"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="ubicacion_tipo",
            field=models.CharField(
                choices=[
                    ("finca", "Finca"),
                    ("vivero", "Vivero"),
                    ("mesa", "Mesa"),
                    ("pared", "Pared"),
                ],
                default="vivero",
                max_length=20,
                verbose_name="Tipo de ubicación",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="tipo_polinizacion",
            field=models.CharField(
                choices=[
                    ("SELF", "Self"),
                    ("HIBRIDO", "Híbrido"),
                    ("SIBBLING", "Sibbling"),
                ],
                max_length=20,
                verbose_name="Tipo de polinización",
            ),
        ),
    ]
