# Generated by Django 5.2.3 on 2025-08-31 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0020_polinizacion_cantidad_capsulas_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="germinacion",
            name="usuario_creador",
        ),
        migrations.AddField(
            model_name="germinacion",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="germinaciones_creadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="nivel",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nivel"
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="no_capsulas",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Número de cápsulas"
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="variedad",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Variedad"
            ),
        ),
        migrations.AlterField(
            model_name="germinacion",
            name="clima",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "Interior"),
                    ("IW", "Interior con ventana"),
                    ("IC", "Interior con calefacción"),
                    ("W", "Exterior con viento"),
                    ("C", "Exterior con calor"),
                ],
                default="I",
                max_length=20,
                null=True,
                verbose_name="Clima",
            ),
        ),
        migrations.AlterField(
            model_name="germinacion",
            name="observaciones",
            field=models.TextField(blank=True, null=True, verbose_name="Observaciones"),
        ),
        migrations.AlterField(
            model_name="germinacion",
            name="ubicacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("percha", "Percha"),
                    ("nivel_1", "Nivel 1"),
                    ("nivel_2", "Nivel 2"),
                    ("nivel_3", "Nivel 3"),
                    ("nivel_4", "Nivel 4"),
                    ("nivel_5", "Nivel 5"),
                ],
                default="percha",
                max_length=20,
                null=True,
                verbose_name="Ubicación",
            ),
        ),
    ]
