# Generated by Django 5.2.3 on 2025-08-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0021_remove_germinacion_usuario_creador_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="germinacion",
            name="especie",
        ),
        migrations.RemoveField(
            model_name="germinacion",
            name="ubicacion",
        ),
        migrations.RemoveField(
            model_name="germinacion",
            name="variedad",
        ),
        migrations.AddField(
            model_name="germinacion",
            name="cantidad_semilla",
            field=models.CharField(
                blank=True,
                choices=[("ABUNDANTE", "Abundante"), ("ESCASA", "Escasa")],
                default="ABUNDANTE",
                max_length=20,
                null=True,
                verbose_name="Cantid. Semilla",
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="clima_lab",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "Interior"),
                    ("IW", "Interior con ventana"),
                    ("IC", "Interior con calefacción"),
                    ("W", "Exterior con viento"),
                    ("C", "Exterior con calor"),
                ],
                default="I",
                max_length=20,
                null=True,
                verbose_name="Clima Lab",
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="especie_variedad",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Especie/Variedad"
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="estado_capsula",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CERRADA", "Cerrada"),
                    ("ABIERTA", "Abierta"),
                    ("SEMIABIERTA", "Semiabierta"),
                ],
                default="CERRADA",
                max_length=20,
                null=True,
                verbose_name="Estado Cápsula",
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="estado_semilla",
            field=models.CharField(
                blank=True,
                choices=[("MADURA", "Madura"), ("TIERNA", "Tierna"), ("VANA", "Vana")],
                default="MADURA",
                max_length=20,
                null=True,
                verbose_name="Semilla",
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="percha",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Percha"
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="semilla_en_stock",
            field=models.BooleanField(default=False, verbose_name="Semilla en Stock"),
        ),
        migrations.AlterField(
            model_name="germinacion",
            name="nivel",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Nivel"
            ),
        ),
    ]
