# Generated by Django 5.2.4 on 2025-09-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0022_remove_germinacion_especie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="rol",
            field=models.CharField(
                choices=[
                    ("TIPO_1", "Técnico de Laboratorio Senior"),
                    ("TIPO_2", "Especialista en Polinización"),
                    ("TIPO_3", "Especialista en Germinación"),
                    ("TIPO_4", "Gestor del Sistema"),
                ],
                default="TIPO_3",
                max_length=10,
            ),
        ),
    ]
