# Generated by Django 5.2.4 on 2025-09-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0023_alter_userprofile_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="germinaciones_actuales",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Germinaciones del mes actual"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="meta_germinaciones",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Meta mensual de germinaciones"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="meta_polinizaciones",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Meta mensual de polinizaciones"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="polinizaciones_actuales",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Polinizaciones del mes actual"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tasa_exito_actual",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Tasa de éxito actual (%)",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tasa_exito_objetivo",
            field=models.PositiveIntegerField(
                default=80, verbose_name="Tasa de éxito objetivo (%)"
            ),
        ),
    ]
