# Generated by Django 5.2.3 on 2025-09-02 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0024_userprofile_germinaciones_actuales_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CondicionesClimaticas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperatura_promedio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Temperatura promedio (°C)",
                    ),
                ),
                (
                    "temperatura_minima",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Temperatura mínima (°C)",
                    ),
                ),
                (
                    "temperatura_maxima",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Temperatura máxima (°C)",
                    ),
                ),
                (
                    "humedad",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Humedad (%)"
                    ),
                ),
                (
                    "precipitacion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Precipitación (mm)",
                    ),
                ),
                (
                    "estacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primavera", "Primavera"),
                            ("verano", "Verano"),
                            ("otoño", "Otoño"),
                            ("invierno", "Invierno"),
                        ],
                        max_length=20,
                        verbose_name="Estación del año",
                    ),
                ),
                (
                    "viento_promedio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Viento promedio (km/h)",
                    ),
                ),
                (
                    "horas_luz",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Horas de luz solar",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Condiciones Climáticas",
                "verbose_name_plural": "Condiciones Climáticas",
            },
        ),
        migrations.CreateModel(
            name="HistorialPredicciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(verbose_name="Fecha inicio del período"),
                ),
                ("fecha_fin", models.DateField(verbose_name="Fecha fin del período")),
                (
                    "total_predicciones",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de predicciones"
                    ),
                ),
                (
                    "predicciones_validadas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Predicciones validadas"
                    ),
                ),
                (
                    "precision_promedio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Precisión promedio (%)",
                    ),
                ),
                (
                    "confianza_promedio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Confianza promedio (%)",
                    ),
                ),
                (
                    "predicciones_iniciales",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Predicciones iniciales"
                    ),
                ),
                (
                    "predicciones_refinadas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Predicciones refinadas"
                    ),
                ),
                (
                    "especie_mas_predicha",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Especie más predicha"
                    ),
                ),
                (
                    "cantidad_especie_top",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad de la especie top"
                    ),
                ),
                (
                    "predicciones_excelentes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Predicciones excelentes (>90%)"
                    ),
                ),
                (
                    "predicciones_buenas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Predicciones buenas (75-90%)"
                    ),
                ),
                (
                    "predicciones_aceptables",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Predicciones aceptables (60-75%)"
                    ),
                ),
                (
                    "predicciones_pobres",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Predicciones pobres (<60%)"
                    ),
                ),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Historial de Predicciones",
                "verbose_name_plural": "Historiales de Predicciones",
                "ordering": ["-fecha_generacion"],
            },
        ),
        migrations.CreateModel(
            name="PrediccionPolinizacion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código de predicción"
                    ),
                ),
                ("especie", models.CharField(max_length=100, verbose_name="Especie")),
                (
                    "genero",
                    models.CharField(blank=True, max_length=100, verbose_name="Género"),
                ),
                (
                    "clima",
                    models.CharField(blank=True, max_length=50, verbose_name="Clima"),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ubicación"
                    ),
                ),
                (
                    "fecha_polinizacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de polinización"
                    ),
                ),
                (
                    "tipo_polinizacion",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tipo de polinización"
                    ),
                ),
                (
                    "dias_estimados",
                    models.PositiveIntegerField(
                        verbose_name="Días estimados hasta semillas"
                    ),
                ),
                (
                    "fecha_estimada_semillas",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha estimada de semillas"
                    ),
                ),
                (
                    "confianza",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Confianza de predicción (%)"
                    ),
                ),
                (
                    "tipo_prediccion",
                    models.CharField(
                        choices=[
                            ("inicial", "Predicción Inicial"),
                            ("refinada", "Predicción Refinada"),
                            ("basica_con_fecha", "Predicción Básica con Fecha"),
                            ("validada", "Predicción Validada"),
                        ],
                        default="inicial",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("validada", "Validada"),
                            ("archivada", "Archivada"),
                        ],
                        default="activa",
                        max_length=20,
                    ),
                ),
                (
                    "archivo_modelo_usado",
                    models.CharField(
                        default="Polinizacion.bin",
                        max_length=100,
                        verbose_name="Archivo del modelo",
                    ),
                ),
                (
                    "version_modelo",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Versión del modelo"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "fecha_maduracion_real",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha real de maduración"
                    ),
                ),
                (
                    "dias_reales",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Días reales hasta semillas"
                    ),
                ),
                (
                    "precision",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Precisión (%)",
                    ),
                ),
                (
                    "desviacion_dias",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Desviación en días"
                    ),
                ),
            ],
            options={
                "verbose_name": "Predicción de Polinización",
                "verbose_name_plural": "Predicciones de Polinización",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.AlterModelOptions(
            name="germinacion",
            options={
                "verbose_name": "Germinación",
                "verbose_name_plural": "Germinaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="polinizacion",
            options={
                "verbose_name": "Polinización",
                "verbose_name_plural": "Polinizaciones",
            },
        ),
        migrations.AddIndex(
            model_name="germinacion",
            index=models.Index(
                fields=["fecha_creacion"], name="laboratorio_fecha_c_aedfb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="germinacion",
            index=models.Index(
                fields=["responsable"], name="laboratorio_respons_87f11e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="germinacion",
            index=models.Index(fields=["codigo"], name="laboratorio_codigo_feb107_idx"),
        ),
        migrations.AddIndex(
            model_name="germinacion",
            index=models.Index(
                fields=["fecha_siembra"], name="laboratorio_fecha_s_9c7931_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="polinizacion",
            index=models.Index(
                fields=["fechapol"], name="laboratorio_fechapo_443e50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="polinizacion",
            index=models.Index(fields=["codigo"], name="laboratorio_codigo_04cbee_idx"),
        ),
        migrations.AddIndex(
            model_name="polinizacion",
            index=models.Index(
                fields=["responsable"], name="laboratorio_respons_857413_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="polinizacion",
            index=models.Index(fields=["estado"], name="laboratorio_estado_280721_idx"),
        ),
        migrations.AddIndex(
            model_name="polinizacion",
            index=models.Index(
                fields=["creado_por"], name="laboratorio_creado__d23862_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="polinizacion",
            index=models.Index(
                fields=["fecha_creacion"], name="laboratorio_fecha_c_dd6f96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="polinizacion",
            index=models.Index(
                fields=["genero", "especie"], name="laboratorio_genero_bed575_idx"
            ),
        ),
        migrations.AddField(
            model_name="historialpredicciones",
            name="usuario_generador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historiales_generados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prediccionpolinizacion",
            name="usuario_creador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predicciones_polinizacion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="condicionesclimaticas",
            name="prediccion",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="condiciones_climaticas",
                to="laboratorio.prediccionpolinizacion",
            ),
        ),
        migrations.AddIndex(
            model_name="prediccionpolinizacion",
            index=models.Index(
                fields=["especie", "fecha_creacion"],
                name="laboratorio_especie_171301_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prediccionpolinizacion",
            index=models.Index(
                fields=["usuario_creador", "estado"],
                name="laboratorio_usuario_eb2e46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prediccionpolinizacion",
            index=models.Index(
                fields=["fecha_polinizacion"], name="laboratorio_fecha_p_83c42c_idx"
            ),
        ),
    ]
