# Generated by Django 5.2.3 on 2025-09-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0025_condicionesclimaticas_historialpredicciones_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polinizacion",
            name="tipo_polinizacion",
            field=models.CharField(
                choices=[
                    ("SELF", "Self"),
                    ("HYBRID", "Hybrid"),
                    ("SIBLING", "Sibling"),
                ],
                max_length=20,
                verbose_name="Tipo de polinización",
            ),
        ),
    ]
