# Generated by Django 5.2.3 on 2025-09-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0027_add_prediction_fields_to_polinizacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polinizacion",
            name="codigo",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="tipo_polinizacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SELF", "Self"),
                    ("HYBRID", "Hybrid"),
                    ("SIBLING", "Sibling"),
                ],
                default="SELF",
                max_length=20,
                verbose_name="Tipo de polinización",
            ),
        ),
    ]
