# Generated by Django 5.2.3 on 2025-09-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0028_fix_polinizacion_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polinizacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("INGRESADO", "Ingresado"),
                    ("EN_PROCESO", "En proceso"),
                    ("LISTA", "Lista"),
                    ("LISTO", "Listo"),
                ],
                default="INGRESADO",
                max_length=20,
                verbose_name="Estado de la polinización",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="tipo_polinizacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SELF", "Self"),
                    ("HYBRID", "Hybrid"),
                    ("SIBLING", "Sibling"),
                    ("Sibbling", "Sibbling"),
                    ("Híbrido", "Híbrido"),
                    ("Autopolinizados", "Autopolinizados"),
                ],
                default="SELF",
                max_length=20,
                verbose_name="Tipo de polinización",
            ),
        ),
    ]
