# Generated by Django 5.2.3 on 2025-09-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0029_update_polinizacion_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="polinizacion",
            name="observaciones",
            field=models.TextField(blank=True, verbose_name="Observaciones"),
        ),
    ]
