# Generated by Django 5.2.3 on 2025-09-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0030_add_observaciones_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="germinacion",
            name="clima",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "Intermedio"),
                    ("IW", "Intermedio Caliente"),
                    ("IC", "Intermedio Frío"),
                    ("W", "Frío"),
                    ("C", "Caliente"),
                ],
                default="I",
                max_length=20,
                null=True,
                verbose_name="Clima",
            ),
        ),
        migrations.AlterField(
            model_name="germinacion",
            name="clima_lab",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "Intermedio"),
                    ("IW", "Intermedio Caliente"),
                    ("IC", "Intermedio Frío"),
                    ("W", "Frío"),
                    ("C", "Caliente"),
                ],
                default="I",
                max_length=20,
                null=True,
                verbose_name="Clima Lab",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="tipo_polinizacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SELF", "Self"),
                    ("SIBLING", "Sibling"),
                    ("HIBRIDA", "Híbrida"),
                ],
                default="SELF",
                max_length=20,
                verbose_name="Tipo de polinización",
            ),
        ),
    ]
