# Generated by Django 5.2.3 on 2025-09-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0030_update_polinizacion_types"),
        ("laboratorio", "0032_add_genero_to_germinacion"),
    ]

    operations = []
