# Generated by Django 4.2.7 on 2025-10-28 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("laboratorio", "0033_merge_20250912_1710"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seguimientogerminacion",
            name="cantidad_germinada",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Cantidad germinada"
            ),
        ),
        migrations.AlterField(
            model_name="seguimientogerminacion",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("SIEMBRA", "Siembra"),
                    ("GERMINACION", "Germinación"),
                    ("CRECIMIENTO", "Crecimiento"),
                    ("TRASPLANTE", "Trasplante"),
                ],
                max_length=20,
                verbose_name="Etapa",
            ),
        ),
        migrations.AlterField(
            model_name="seguimientogerminacion",
            name="fecha",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de seguimiento"
            ),
        ),
        migrations.AlterField(
            model_name="seguimientogerminacion",
            name="observaciones",
            field=models.TextField(blank=True, verbose_name="Observaciones"),
        ),
        migrations.AlterField(
            model_name="seguimientogerminacion",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seguimientos_germinacion",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
    ]
