# Generated by Django 4.2.7 on 2025-10-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0034_fix_seguimiento_fecha_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="germinacion",
            name="prediccion_condiciones_climaticas",
            field=models.TextField(
                blank=True, verbose_name="Condiciones climáticas de predicción"
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="prediccion_confianza",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Confianza de predicción (%)",
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="prediccion_dias_estimados",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Días estimados de predicción"
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="prediccion_especie_info",
            field=models.TextField(
                blank=True, verbose_name="Información de especie de predicción"
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="prediccion_fecha_estimada",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha estimada de germinación"
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="prediccion_parametros_usados",
            field=models.TextField(
                blank=True, verbose_name="Parámetros usados en predicción"
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="prediccion_tipo",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Tipo de predicción"
            ),
        ),
    ]
