# Generated by Django 5.2.3 on 2025-10-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0035_germinacion_prediccion_condiciones_climaticas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="germinacion",
            name="etapa_actual",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INGRESADO", "Ingresado"),
                    ("EN_PROCESO", "En proceso"),
                    ("LISTA", "Lista"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="INGRESADO",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="fechapol",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de polinización"
            ),
        ),
    ]
