# Generated by Django 5.2.3 on 2025-10-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0036_alter_germinacion_etapa_actual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polinizacion",
            name="especie",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
