# Generated by Django 5.2.3 on 2025-10-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0037_alter_polinizacion_especie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="germinacion",
            name="codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="Código",
            ),
        ),
    ]
