# Generated by Django 5.2.3 on 2025-11-04 00:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0038_alter_germinacion_codigo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="archivada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="detalles_adicionales",
            field=models.JSONField(
                blank=True, help_text="Detalles adicionales en formato JSON", null=True
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="favorita",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("NUEVA_GERMINACION", "Nueva Germinación"),
                    ("RECORDATORIO_REVISION", "Recordatorio de Revisión"),
                    ("ESTADO_ACTUALIZADO", "Estado Actualizado"),
                    ("NUEVA_POLINIZACION", "Nueva Polinización"),
                    (
                        "ESTADO_POLINIZACION_ACTUALIZADO",
                        "Estado de Polinización Actualizado",
                    ),
                    ("MENSAJE", "Mensaje"),
                    ("ERROR", "Error"),
                    ("ACTUALIZACION", "Actualización"),
                ],
                max_length=35,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["usuario", "-fecha_creacion"],
                name="laboratorio_usuario_ea6246_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["usuario", "leida"], name="laboratorio_usuario_d45a19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["usuario", "archivada"], name="laboratorio_usuario_4d6cd7_idx"
            ),
        ),
    ]
