# Generated by Django 5.2.3 on 2025-11-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0039_add_notification_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polinizacion",
            name="codigo",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
