# Generated by Django 5.2.3 on 2025-11-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0040_alter_polinizacion_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="polinizacion",
            name="mesa",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Mesa (ej: M-1A)"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="pared",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Pared (ej: P-C)"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="vivero",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Vivero (ej: V-13)"
            ),
        ),
    ]
