# Generated by Django 5.2.3 on 2025-11-11 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0002_rename_usuario_to_user"),
        ("laboratorio", "0041_polinizacion_mesa_polinizacion_pared_and_more"),
    ]

    operations = []
