# Generated by Django 5.2.3 on 2025-11-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0042_merge_20251110_2200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polinizacion",
            name="madre_clima",
            field=models.CharField(
                blank=True,
                default="I",
                max_length=50,
                verbose_name="Clima planta madre",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="madre_codigo",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Código planta madre",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="madre_especie",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Especie/Variedad planta madre",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="madre_genero",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Género planta madre",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="nueva_clima",
            field=models.CharField(
                blank=True,
                default="I",
                max_length=50,
                verbose_name="Clima nueva planta",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="nueva_codigo",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Código nueva planta",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="nueva_especie",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Especie/Variedad nueva planta",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="nueva_genero",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Género nueva planta",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="padre_clima",
            field=models.CharField(
                blank=True,
                default="I",
                max_length=50,
                verbose_name="Clima planta padre",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="padre_codigo",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Código planta padre",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="padre_especie",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Especie/Variedad planta padre",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="padre_genero",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Género planta padre",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="ubicacion_nombre",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Nombre de ubicación",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="ubicacion_tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("finca", "Finca"),
                    ("vivero", "Vivero"),
                    ("mesa", "Mesa"),
                    ("pared", "Pared"),
                ],
                default="vivero",
                max_length=20,
                verbose_name="Tipo de ubicación",
            ),
        ),
    ]
