# Generated by Django 5.2.3 on 2025-12-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0047_add_estado_progreso_polinizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="germinacion",
            name="archivo_origen",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Archivo de origen"
            ),
        ),
    ]
