# Generated by Django 5.2.3 on 2025-12-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0048_germinacion_archivo_origen"),
    ]

    operations = [
        migrations.AddField(
            model_name="germinacion",
            name="estado_validacion",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Estado de validación",
            ),
        ),
    ]
