# Generated by Django 5.2.3 on 2025-12-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0049_germinacion_estado_validacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_photos/",
                verbose_name="Foto de perfil",
            ),
        ),
    ]
