# Generated by Django 5.2.3 on 2025-12-17 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0050_userprofile_foto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Creación"),
                            ("UPDATE", "Actualización"),
                            ("DELETE", "Eliminación"),
                            ("LOGIN", "Inicio de sesión"),
                            ("LOGOUT", "Cierre de sesión"),
                            ("PASSWORD_CHANGE", "Cambio de contraseña"),
                            ("STATUS_CHANGE", "Cambio de estado"),
                            ("BULK_OPERATION", "Operación en lote"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("USER", "Usuario"),
                            ("GERMINACION", "Germinación"),
                            ("POLINIZACION", "Polinización"),
                            ("USERPROFILE", "Perfil de Usuario"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de entidad",
                    ),
                ),
                (
                    "entity_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID de entidad"
                    ),
                ),
                (
                    "entity_repr",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Representación de entidad",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Cambios realizados"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoría",
                "verbose_name_plural": "Logs de Auditoría",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="laboratorio_timesta_fd0edb_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="laboratorio_user_id_933ce6_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="laboratorio_entity__20fabf_idx",
                    ),
                ],
            },
        ),
    ]
