# Generated by Django 5.2.3 on 2025-12-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0051_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polinizacion",
            name="progreso_polinizacion",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Porcentaje de progreso de la polinización (0-100%)",
                verbose_name="Progreso de Polinización (%)",
            ),
        ),
    ]
