# Generated by Django 5.2.3 on 2025-12-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0053_actualizar_estados_polinizacion_granular"),
    ]

    operations = [
        migrations.AlterField(
            model_name="germinacion",
            name="estado_germinacion",
            field=models.CharField(
                choices=[
                    ("INICIAL", "Inicial"),
                    ("EN_PROCESO_TEMPRANO", "En Proceso - Temprano"),
                    ("EN_PROCESO_AVANZADO", "En Proceso - Avanzado"),
                    ("FINALIZADO", "Finalizado"),
                ],
                default="INICIAL",
                help_text="Estado del proceso de germinación",
                max_length=20,
                verbose_name="Estado de Germinación",
            ),
        ),
        migrations.AlterField(
            model_name="germinacion",
            name="progreso_germinacion",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Porcentaje de progreso de la germinación (0-100%)",
                verbose_name="Progreso de Germinación (%)",
            ),
        ),
    ]
