# Generated by Django 5.2.3 on 2025-12-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0054_actualizar_estados_germinacion_granular"),
    ]

    operations = [
        migrations.AddField(
            model_name="germinacion",
            name="alerta_revision_enviada",
            field=models.BooleanField(
                default=False, verbose_name="Alerta de revisión enviada"
            ),
        ),
        migrations.AddField(
            model_name="germinacion",
            name="fecha_proxima_revision",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de próxima revisión"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="alerta_revision_enviada",
            field=models.BooleanField(
                default=False, verbose_name="Alerta de revisión enviada"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="fecha_proxima_revision",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de próxima revisión"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="fecha_ultima_revision",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de última revisión"
            ),
        ),
        migrations.AlterField(
            model_name="germinacion",
            name="fecha_ultima_revision",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de última revisión"
            ),
        ),
    ]
