# Generated by Django 5.2.3 on 2026-01-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0055_agregar_sistema_alertas_revision"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="polinizacion",
            name="alerta_revision_enviada",
        ),
        migrations.RemoveField(
            model_name="polinizacion",
            name="fecha_proxima_revision",
        ),
        migrations.RemoveField(
            model_name="polinizacion",
            name="fecha_ultima_revision",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="foto",
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="cantidad_disponible",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Cantidad disponible"
            ),
        ),
        migrations.AddField(
            model_name="polinizacion",
            name="cantidad_solicitada",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Cantidad solicitada"
            ),
        ),
        migrations.AlterField(
            model_name="germinacion",
            name="estado_germinacion",
            field=models.CharField(
                choices=[
                    ("INICIAL", "Inicial"),
                    ("EN_PROCESO", "En Proceso"),
                    ("FINALIZADO", "Finalizado"),
                ],
                default="INICIAL",
                help_text="Estado del proceso de germinación",
                max_length=20,
                verbose_name="Estado de Germinación",
            ),
        ),
        migrations.AlterField(
            model_name="germinacion",
            name="fecha_proxima_revision",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha próxima revisión"
            ),
        ),
        migrations.AlterField(
            model_name="germinacion",
            name="fecha_ultima_revision",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="germinacion",
            name="progreso_germinacion",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Porcentaje de progreso de la germinación (0-100%)",
                verbose_name="Progreso de Germinación (%)",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="estado_polinizacion",
            field=models.CharField(
                choices=[
                    ("INICIAL", "Inicial"),
                    ("EN_PROCESO", "En Proceso"),
                    ("FINALIZADO", "Finalizado"),
                ],
                default="INICIAL",
                help_text="Estado del proceso de polinización",
                max_length=20,
                verbose_name="Estado de Polinización",
            ),
        ),
        migrations.AlterField(
            model_name="polinizacion",
            name="progreso_polinizacion",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Porcentaje de progreso de la polinización (0-100%)",
                verbose_name="Progreso de Polinización (%)",
            ),
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
    ]
