# Generated by Django 5.2.3 on 2026-01-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0057_add_alertas_automaticas_polinizacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("NUEVA_GERMINACION", "Nueva Germinación"),
                    ("RECORDATORIO_REVISION", "Recordatorio de Revisión"),
                    ("RECORDATORIO_5_DIAS", "Recordatorio 5 Días"),
                    ("RECORDATORIO_PREDICCION", "Recordatorio de Predicción"),
                    ("ESTADO_ACTUALIZADO", "Estado Actualizado"),
                    ("NUEVA_POLINIZACION", "Nueva Polinización"),
                    (
                        "ESTADO_POLINIZACION_ACTUALIZADO",
                        "Estado de Polinización Actualizado",
                    ),
                    ("MENSAJE", "Mensaje"),
                    ("ERROR", "Error"),
                    ("ACTUALIZACION", "Actualización"),
                ],
                max_length=35,
            ),
        ),
    ]
