# Generated by Django 5.2.3 on 2026-02-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0058_alter_notification_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polinizacion",
            name="nueva_especie",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Especie/Variedad nueva planta",
            ),
        ),
    ]
