# Generated by Django 5.2.3 on 2026-03-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0060_add_estados_polinizacion_granular"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="debe_cambiar_password",
            field=models.BooleanField(
                default=False,
                help_text="Si es True, el usuario debe cambiar su contraseña antes de usar el sistema.",
                verbose_name="Debe cambiar contraseña",
            ),
        ),
    ]
