"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env
from dotenv import load_dotenv
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-td5k-97f$l!p6(p19j3d6+p$3e#3vr*9i9*5^d+)5(9mjsmphw')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'laboratorio',
    'django_extensions',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_apscheduler',  # Scheduler para tareas automáticas
    'drf_spectacular',     # Documentación Swagger / OpenAPI
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# Database Configuration
# Soporta SQLite (desarrollo) y PostgreSQL (producción) según variables de entorno
# Detecta automáticamente GitHub Codespaces y usa SQLite por defecto

# Detectar si estamos en GitHub Codespaces
IS_CODESPACES = os.environ.get('CODESPACES', 'false') == 'true'
IS_GITHUB_WORKSPACE = 'GITHUB_WORKSPACE' in os.environ

# Configurar engine según entorno
if IS_CODESPACES or IS_GITHUB_WORKSPACE:
    # En Codespaces, usar SQLite por defecto (más fácil)
    DB_ENGINE = os.environ.get('DB_ENGINE', 'sqlite3').lower()
    print(f"🔵 Entorno detectado: GitHub Codespaces - Usando {DB_ENGINE.upper()}")
else:
    # En desarrollo local, usar lo que esté en .env
    DB_ENGINE = os.environ.get('DB_ENGINE', 'sqlite3').lower()

if DB_ENGINE == 'postgresql':
    # Configuración para PostgreSQL (Producción o Local)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get('DB_NAME', 'laboratorio_db'),
            "USER": os.environ.get('DB_USER', 'laboratorio_user'),
            "PASSWORD": os.environ.get('DB_PASSWORD', 'root'),
            "HOST": os.environ.get('DB_HOST', 'localhost'),
            "PORT": os.environ.get('DB_PORT', '5432'),
            "OPTIONS": {
                "connect_timeout": 10,
            },
            "CONN_MAX_AGE": 600 if not DEBUG else 60,  # 10 min en prod, 1 min en dev
        }
    }
else:
    # Configuración para SQLite (Desarrollo por defecto y Codespaces)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / os.environ.get('DB_NAME', 'db.sqlite3'),
        }
    }

# JWT Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'laboratorio.renderers.BinaryFileRenderer',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ============================================================================
# CONFIGURACIÓN SWAGGER / OPENAPI (drf-spectacular)
# ============================================================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'PoliGer API',
    'DESCRIPTION': (
        'API REST para el Sistema de Gestión de Polinización y Germinación de EcuaGenera.\n\n'
        '## Autenticación\n'
        'Esta API usa **JWT (Bearer Token)**. Para autenticarte:\n'
        '1. Llama a `POST /api/token/` con tus credenciales.\n'
        '2. Copia el campo `access` de la respuesta.\n'
        '3. En el botón **Authorize** (arriba a la derecha), ingresa: `Bearer <tu_token>`.\n\n'
        '## Módulos principales\n'
        '- **Autenticación**: Registro, login y tokens JWT.\n'
        '- **Polinizaciones**: Gestión completa del proceso de polinización.\n'
        '- **Germinaciones**: Seguimiento de germinación con estados y alertas.\n'
        '- **Predicciones ML**: Modelos XGBoost y Random Forest para predicciones.\n'
        '- **Inventario**: Gestión de géneros, especies, cápsulas y siembras.\n'
        '- **Notificaciones**: Sistema de notificaciones y recordatorios.\n'
        '- **Usuarios**: Gestión de perfiles y sistema RBAC.\n'
        '- **Estadísticas y Reportes**: Reportes en PDF y análisis estadístico.'
    ),
    'VERSION': '1.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Agrupar endpoints por tags
    'TAGS': [
        {'name': 'Autenticación', 'description': 'Registro, login y gestión de tokens JWT.'},
        {'name': 'Polinizaciones', 'description': 'Gestión del proceso de polinización.'},
        {'name': 'Germinaciones', 'description': 'Seguimiento del proceso de germinación.'},
        {'name': 'Seguimientos', 'description': 'Seguimiento detallado de germinaciones.'},
        {'name': 'Géneros', 'description': 'Catálogo de géneros botánicos.'},
        {'name': 'Especies', 'description': 'Catálogo de especies botánicas.'},
        {'name': 'Ubicaciones', 'description': 'Gestión de ubicaciones del laboratorio.'},
        {'name': 'Cápsulas', 'description': 'Gestión de cápsulas.'},
        {'name': 'Siembras', 'description': 'Gestión de siembras.'},
        {'name': 'Personal', 'description': 'Gestión del personal del laboratorio.'},
        {'name': 'Inventario', 'description': 'Gestión del inventario.'},
        {'name': 'Notificaciones', 'description': 'Sistema de notificaciones y alertas.'},
        {'name': 'Usuarios', 'description': 'Gestión de perfiles y roles (RBAC).'},
        {'name': 'Predicciones', 'description': 'Predicciones estadísticas y con Machine Learning.'},
        {'name': 'Estadísticas', 'description': 'Reportes y estadísticas del sistema.'},
        {'name': 'Importación CSV', 'description': 'Importación masiva de datos desde archivos CSV.'},
        {'name': 'Salud', 'description': 'Health check y endpoints de estado del sistema.'},
    ],
    # Seguridad: JWT Bearer
    'SECURITY': [{'jwtAuth': []}],
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'ENUM_GENERATE_CHOICE_DESCRIPTION': True,
    'SORT_OPERATIONS': False,
    # Hook para renombrar tags auto-generados al español
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums',
        'laboratorio.swagger_hooks.rename_tags_hook',
    ],
    # UI personalizada
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
        'docExpansion': 'list',
        'filter': True,
        'tryItOutEnabled': True,
    },
    'SWAGGER_UI_FAVICON_HREF': None,
    'REDOC_UI_SETTINGS': {
        'hideDownloadButton': False,
        'expandResponses': '200,201',
    },
}

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "es-es"
TIME_ZONE = "America/Bogota"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Solo True en desarrollo
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8081",
    "http://127.0.0.1:8081",
    "exp://localhost:8081",
    "exp://127.0.0.1:8081",
    "http://207.180.230.88",
    "http://207.180.230.88:8000",
    "http://207.180.230.88:19006",  # Expo default port
    "http://207.180.230.88:3000",
    # Dominios de producción
    "http://www.poligerecuagenera.org",
    "https://www.poligerecuagenera.org",
    "http://poligerecuagenera.org",
    "https://poligerecuagenera.org",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Security Settings
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Logging Configuration
import os

# Crear directorio de logs si no existe
log_dir = BASE_DIR / 'logs'
log_dir.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': log_dir / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'laboratorio': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# Cache Configuration - Optimized for development
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,
        }
    }
}

# Database connection optimizations
# Aplicar solo optimizaciones compatibles según el engine
if DB_ENGINE == 'sqlite3':
    DATABASES['default'].update({
        'OPTIONS': {
            'timeout': 20,  # Increase timeout for better stability with SQLite
            # SQLite optimizations are applied via signal in apps.py
        }
    })
# Para PostgreSQL, CONN_MAX_AGE ya se configuró arriba

# Model ML Cache
ML_MODEL_CACHE_TIMEOUT = 3600  # 1 hora

# ============================================================================
# CONFIGURACIÓN DE SCHEDULER (APScheduler)
# ============================================================================
# Configuración para tareas programadas automáticas

APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"  # Formato de fecha para logs

APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Segundos antes de timeout

# Configuración de tareas programadas
SCHEDULER_CONFIG = {
    'apscheduler.jobstores.default': {
        'type': 'memory'  # Usar memoria para desarrollo (cambiar a 'sqlalchemy' en producción)
    },
    'apscheduler.executors.default': {
        'class': 'apscheduler.executors.pool:ThreadPoolExecutor',
        'max_workers': '5'
    },
    'apscheduler.job_defaults.coalesce': 'false',
    'apscheduler.job_defaults.max_instances': '3',
}

# Intervalo de verificación de notificaciones (en minutos)
NOTIFICATION_CHECK_INTERVAL_MINUTES = 60  # Verificar cada hora

# Días después de fecha base para enviar recordatorio
NOTIFICATION_REMINDER_DAYS = 5

# ============================================================================
# EMAIL CONFIGURATION (Gmail SMTP)
# ============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER', 'noreply@poliger.com')

# URL y nombre de la aplicación (para enlaces en emails)
APP_URL = 'http://207.180.230.88'
APP_NAME = 'PoliGer - EcuaGenera'
